// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgmxiEqwgr0zr5OTITPzHJf_J9M99vnI',
    appId: '1:29478481205:web:dfe30e6b19daee71e4f07c',
    messagingSenderId: '29478481205',
    projectId: 'capicoins',
    authDomain: 'capicoins.firebaseapp.com',
    storageBucket: 'capicoins.firebasestorage.app',
    measurementId: 'G-1T7C911N77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5VxEIhsoBVE7ofM63VgphUbO8qfVZato',
    appId: '1:29478481205:android:6b349c20bb6a1315e4f07c',
    messagingSenderId: '29478481205',
    projectId: 'capicoins',
    storageBucket: 'capicoins.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOjY2F1N3mFeTzYRLw9v0KNHwQwAQT7qM',
    appId: '1:29478481205:ios:0b2e1493656b929de4f07c',
    messagingSenderId: '29478481205',
    projectId: 'capicoins',
    storageBucket: 'capicoins.firebasestorage.app',
    iosBundleId: 'com.example.capiCoins',
  );
}
